import 'dotenv/config'
import bcrypt from 'bcryptjs'
import mongoose from 'mongoose'
import User from '../models/User.js'
import Recipe from '../models/Recipe.js'
import Review from '../models/Review.js'
import Follow from '../models/Follow.js'
import Like from '../models/Like.js'

// ─── Connect ────────────────────────────────────────────────────────────────
await mongoose.connect(process.env.MONGODB_URI)
console.log('✅ Connected to MongoDB\n')

// ─── Users ──────────────────────────────────────────────────────────────────
const usersData = [
  {
    displayName: 'Gordon Ramsay',
    email: 'gordon@recipenest.com',
    password: 'Gordon@1234',
    aboutMe: 'Michelin-starred chef, restaurateur, and television personality known for his fiery passion and uncompromising standards in the kitchen.',
    contactLinks: 'https://gordonramsay.com',
    socialMediaLinks: 'https://twitter.com/GordonRamsay | https://instagram.com/gordongram',
  },
  {
    displayName: 'Julia Child',
    email: 'julia@recipenest.com',
    password: 'Julia@1234',
    aboutMe: 'Legendary American cooking teacher and author who introduced French cuisine to the American public through her books and television shows.',
    contactLinks: 'https://juliachildfoundation.org',
    socialMediaLinks: 'https://instagram.com/juliachild',
  },
  {
    displayName: 'Jamie Oliver',
    email: 'jamie@recipenest.com',
    password: 'Jamie@1234',
    aboutMe: 'British chef and food activist dedicated to making fresh, simple, and delicious food accessible to everyone around the world.',
    contactLinks: 'https://jamieoliver.com',
    socialMediaLinks: 'https://twitter.com/jamieoliver | https://instagram.com/jamieoliver',
  },
  {
    displayName: 'Yotam Ottolenghi',
    email: 'yotam@recipenest.com',
    password: 'Yotam@1234',
    aboutMe: 'Israeli-British chef and food writer celebrated for vibrant, vegetable-forward dishes inspired by Middle Eastern and Mediterranean flavours.',
    contactLinks: 'https://ottolenghi.co.uk',
    socialMediaLinks: 'https://twitter.com/ottolenghi | https://instagram.com/ottolenghi',
  },
  {
    displayName: 'Nigella Lawson',
    email: 'nigella@recipenest.com',
    password: 'Nigella@1234',
    aboutMe: 'British food writer and television cook who champions the joy of cooking and eating without guilt, blending indulgence with everyday simplicity.',
    contactLinks: 'https://nigella.com',
    socialMediaLinks: 'https://twitter.com/nigellalawson | https://instagram.com/nigellalawson',
  },
  {
    displayName: 'Thomas Keller',
    email: 'thomas@recipenest.com',
    password: 'Thomas@1234',
    aboutMe: 'Acclaimed American chef and restaurateur behind The French Laundry and Per Se, renowned for his meticulous technique and pursuit of perfection.',
    contactLinks: 'https://thomaskeller.com',
    socialMediaLinks: 'https://instagram.com/thomaskeller',
  },
  {
    displayName: 'Ina Garten',
    email: 'ina@recipenest.com',
    password: 'Ina@12345',
    aboutMe: 'The Barefoot Contessa herself — Ina creates elegant yet approachable recipes that make entertaining at home feel effortless and joyful.',
    contactLinks: 'https://barefootcontessa.com',
    socialMediaLinks: 'https://twitter.com/inagarten | https://instagram.com/inagarten',
  },
  {
    displayName: 'Heston Blumenthal',
    email: 'heston@recipenest.com',
    password: 'Heston@1234',
    aboutMe: 'Pioneering British chef and food scientist who pushes the boundaries of gastronomy with multi-sensory dining experiences at The Fat Duck.',
    contactLinks: 'https://thefatduck.co.uk',
    socialMediaLinks: 'https://twitter.com/hestonb | https://instagram.com/hestonblumenthal',
  },
  {
    displayName: 'Massimo Bottura',
    email: 'massimo@recipenest.com',
    password: 'Massimo@1234',
    aboutMe: 'Italian chef and owner of Osteria Francescana, three-time world\'s best restaurant, reimagining Italian culinary tradition through art and culture.',
    contactLinks: 'https://osteriafrancescana.it',
    socialMediaLinks: 'https://twitter.com/massimobottura | https://instagram.com/massimobottura',
  },
  {
    displayName: 'Nobu Matsuhisa',
    email: 'nobu@recipenest.com',
    password: 'Nobu@1234',
    aboutMe: 'World-renowned Japanese chef who fused traditional Japanese techniques with Peruvian ingredients to create a globally celebrated culinary style.',
    contactLinks: 'https://noburestaurants.com',
    socialMediaLinks: 'https://twitter.com/noburestaurants | https://instagram.com/noburestaurants',
  },
]

const createdUsers = {}
for (const u of usersData) {
  let user = await User.findOne({ email: u.email })
  if (!user) {
    const passwordHash = await bcrypt.hash(u.password, 10)
    user = await User.create({
      displayName: u.displayName,
      email: u.email,
      passwordHash,
      aboutMe: u.aboutMe,
      contactLinks: u.contactLinks,
      socialMediaLinks: u.socialMediaLinks,
    })
    console.log(`  ✔ Created user: ${u.displayName}`)
  } else {
    console.log(`  – Skipped user (exists): ${u.displayName}`)
  }
  createdUsers[u.email] = user
}

const [gordon, julia, jamie, yotam, nigella, thomas, ina, heston, massimo, nobu] = usersData.map(u => createdUsers[u.email])

// --- Recipes -----------------------------------------------------------------
const recipesData = [
  // -- Gordon Ramsay (5 recipes) ----------------------------------------------
  {
    title: 'Beef Wellington',
    description: 'Gordon\'s signature dish � a perfectly seared beef tenderloin wrapped in mushroom duxelles and golden puff pastry.',
    category: 'Dinner',
    difficulty: 'Hard',
    preparationTimeMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    authorEmail: 'gordon@recipenest.com',
    ingredients: [
      { name: 'Beef tenderloin', quantity: '1 kg', orderIndex: 0 },
      { name: 'Puff pastry', quantity: '500 g', orderIndex: 1 },
      { name: 'Mushrooms (chestnut)', quantity: '400 g', orderIndex: 2 },
      { name: 'Prosciutto', quantity: '12 slices', orderIndex: 3 },
      { name: 'Dijon mustard', quantity: '2 tbsp', orderIndex: 4 },
      { name: 'Egg yolk', quantity: '2', orderIndex: 5 },
      { name: 'Garlic cloves', quantity: '3', orderIndex: 6 },
      { name: 'Fresh thyme', quantity: '4 sprigs', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Season the beef tenderloin generously with salt and pepper. Sear in a hot oiled pan for 2 minutes on each side until browned all over. Brush with Dijon mustard and let cool completely.', orderIndex: 0 },
      { stepText: 'Blitz mushrooms, garlic, and thyme in a food processor. Cook the duxelles in a dry pan over medium heat, stirring constantly, until all moisture has evaporated (about 10 minutes). Season and cool.', orderIndex: 1 },
      { stepText: 'Lay out a sheet of cling film. Arrange prosciutto slices in an overlapping layer. Spread the mushroom duxelles evenly over the prosciutto. Place the beef at the edge and roll tightly into a log. Refrigerate for 30 minutes.', orderIndex: 2 },
      { stepText: 'Roll out puff pastry on a floured surface. Unwrap the beef roll and place on the pastry. Wrap tightly, sealing the edges with egg wash. Score the top lightly and brush all over with egg yolk.', orderIndex: 3 },
      { stepText: 'Bake in a preheated oven at 220�C (425�F) for 25�30 minutes until the pastry is deep golden. Rest for 10 minutes before slicing and serving.', orderIndex: 4 },
    ],
  },
  {
    title: 'Pan-Seared Salmon with Lemon Butter',
    description: 'Crispy-skinned salmon fillets finished with a bright, silky lemon butter sauce � restaurant quality in under 20 minutes.',
    category: 'Dinner',
    difficulty: 'Easy',
    preparationTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800',
    authorEmail: 'gordon@recipenest.com',
    ingredients: [
      { name: 'Salmon fillets (skin-on)', quantity: '4 x 180 g', orderIndex: 0 },
      { name: 'Unsalted butter', quantity: '60 g', orderIndex: 1 },
      { name: 'Lemon', quantity: '1', orderIndex: 2 },
      { name: 'Garlic cloves', quantity: '2', orderIndex: 3 },
      { name: 'Fresh dill', quantity: '2 tbsp', orderIndex: 4 },
      { name: 'Olive oil', quantity: '2 tbsp', orderIndex: 5 },
      { name: 'Salt and black pepper', quantity: 'to taste', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Pat salmon fillets dry with paper towels. Season both sides with salt and pepper.', orderIndex: 0 },
      { stepText: 'Heat olive oil in a non-stick pan over high heat until shimmering. Place salmon skin-side down and press gently for 10 seconds. Cook for 4 minutes without moving.', orderIndex: 1 },
      { stepText: 'Flip the salmon and add butter and crushed garlic to the pan. Cook for 2 more minutes, basting continuously with the foaming butter.', orderIndex: 2 },
      { stepText: 'Squeeze lemon juice into the pan and scatter fresh dill. Serve immediately with the pan juices spooned over.', orderIndex: 3 },
    ],
  },
  {
    title: 'Classic Beef Stew',
    description: 'A hearty, slow-cooked beef stew with root vegetables in a rich red wine gravy � the ultimate comfort food.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800',
    authorEmail: 'gordon@recipenest.com',
    ingredients: [
      { name: 'Beef chuck, cubed', quantity: '800 g', orderIndex: 0 },
      { name: 'Carrots', quantity: '3 large', orderIndex: 1 },
      { name: 'Potatoes', quantity: '4 medium', orderIndex: 2 },
      { name: 'Red wine', quantity: '250 ml', orderIndex: 3 },
      { name: 'Beef stock', quantity: '500 ml', orderIndex: 4 },
      { name: 'Tomato paste', quantity: '2 tbsp', orderIndex: 5 },
      { name: 'Onion', quantity: '2 large', orderIndex: 6 },
      { name: 'Fresh rosemary', quantity: '2 sprigs', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Season beef cubes with salt and pepper. Brown in batches in a hot Dutch oven with oil until deeply caramelised on all sides. Remove and set aside.', orderIndex: 0 },
      { stepText: 'In the same pot, saut� diced onions until soft. Add tomato paste and cook for 2 minutes. Pour in red wine and scrape up all the browned bits.', orderIndex: 1 },
      { stepText: 'Return beef to the pot. Add stock, rosemary, carrots, and potatoes. Bring to a boil, then reduce to a low simmer.', orderIndex: 2 },
      { stepText: 'Cover and cook for 2�2.5 hours until the beef is fork-tender and the sauce has thickened. Adjust seasoning and serve with crusty bread.', orderIndex: 3 },
    ],
  },
  {
    title: 'Perfect Scrambled Eggs',
    description: 'Gordon\'s famous low-and-slow scrambled eggs � impossibly creamy, soft, and luxurious with cr�me fra�che and chives.',
    category: 'Breakfast',
    difficulty: 'Easy',
    preparationTimeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    authorEmail: 'gordon@recipenest.com',
    ingredients: [
      { name: 'Large eggs', quantity: '6', orderIndex: 0 },
      { name: 'Unsalted butter', quantity: '30 g', orderIndex: 1 },
      { name: 'Cr�me fra�che', quantity: '2 tbsp', orderIndex: 2 },
      { name: 'Fresh chives', quantity: '1 tbsp, chopped', orderIndex: 3 },
      { name: 'Salt and black pepper', quantity: 'to taste', orderIndex: 4 },
      { name: 'Sourdough toast', quantity: '2 slices', orderIndex: 5 },
    ],
    instructions: [
      { stepText: 'Crack eggs directly into a cold non-stick pan. Add butter. Place over medium-low heat.', orderIndex: 0 },
      { stepText: 'Stir constantly with a rubber spatula, moving the eggs around the pan. Every 30 seconds, take the pan off the heat and keep stirring � this controls the temperature.', orderIndex: 1 },
      { stepText: 'When the eggs are just barely set and still look slightly underdone, remove from heat. Stir in cr�me fra�che to stop the cooking.', orderIndex: 2 },
      { stepText: 'Season with salt and pepper, scatter chives, and serve immediately on toasted sourdough.', orderIndex: 3 },
    ],
  },
  {
    title: 'Sticky BBQ Ribs',
    description: 'Fall-off-the-bone pork ribs slow-cooked then glazed with a smoky, sticky barbecue sauce.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 210,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    authorEmail: 'gordon@recipenest.com',
    ingredients: [
      { name: 'Pork baby back ribs', quantity: '2 racks', orderIndex: 0 },
      { name: 'Smoked paprika', quantity: '2 tbsp', orderIndex: 1 },
      { name: 'Brown sugar', quantity: '3 tbsp', orderIndex: 2 },
      { name: 'Garlic powder', quantity: '1 tbsp', orderIndex: 3 },
      { name: 'Ketchup', quantity: '200 ml', orderIndex: 4 },
      { name: 'Apple cider vinegar', quantity: '3 tbsp', orderIndex: 5 },
      { name: 'Worcestershire sauce', quantity: '2 tbsp', orderIndex: 6 },
      { name: 'Honey', quantity: '2 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Mix paprika, brown sugar, garlic powder, salt, and pepper. Rub all over the ribs. Wrap tightly in foil and refrigerate for at least 1 hour.', orderIndex: 0 },
      { stepText: 'Bake foil-wrapped ribs at 150�C (300�F) for 2.5 hours until very tender.', orderIndex: 1 },
      { stepText: 'Combine ketchup, vinegar, Worcestershire, and honey in a saucepan. Simmer for 10 minutes until thickened into a glaze.', orderIndex: 2 },
      { stepText: 'Unwrap ribs, brush generously with glaze, and grill or broil for 5�8 minutes per side until caramelised and sticky. Serve with extra sauce.', orderIndex: 3 },
    ],
  },
  // -- Julia Child (5 recipes) ------------------------------------------------
  {
    title: 'Classic French Onion Soup',
    description: 'Julia\'s beloved French onion soup with deeply caramelised onions, rich beef broth, and a bubbling Gruy�re crouton on top.',
    category: 'Soup',
    difficulty: 'Medium',
    preparationTimeMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
    authorEmail: 'julia@recipenest.com',
    ingredients: [
      { name: 'Yellow onions', quantity: '1.5 kg', orderIndex: 0 },
      { name: 'Unsalted butter', quantity: '50 g', orderIndex: 1 },
      { name: 'Beef stock', quantity: '1.5 litres', orderIndex: 2 },
      { name: 'Dry white wine', quantity: '150 ml', orderIndex: 3 },
      { name: 'Baguette slices', quantity: '8', orderIndex: 4 },
      { name: 'Gruy�re cheese, grated', quantity: '200 g', orderIndex: 5 },
      { name: 'Fresh thyme', quantity: '3 sprigs', orderIndex: 6 },
      { name: 'Bay leaf', quantity: '1', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Slice onions thinly. Melt butter in a large heavy pot over medium heat. Add onions and cook, stirring occasionally, for 45�60 minutes until deeply golden and caramelised.', orderIndex: 0 },
      { stepText: 'Add white wine and scrape up any browned bits. Pour in beef stock, add thyme and bay leaf. Simmer for 20 minutes. Season with salt and pepper.', orderIndex: 1 },
      { stepText: 'Toast baguette slices until crisp. Ladle soup into oven-safe bowls, float a crouton on top, and pile with Gruy�re.', orderIndex: 2 },
      { stepText: 'Place bowls under a hot broiler for 3�4 minutes until the cheese is bubbling and golden. Serve immediately.', orderIndex: 3 },
    ],
  },
  {
    title: 'Boeuf Bourguignon',
    description: 'The quintessential French braised beef stew with pearl onions, mushrooms, and a silky red wine sauce.',
    category: 'Dinner',
    difficulty: 'Hard',
    preparationTimeMinutes: 240,
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    authorEmail: 'julia@recipenest.com',
    ingredients: [
      { name: 'Beef chuck, cubed', quantity: '1 kg', orderIndex: 0 },
      { name: 'Burgundy red wine', quantity: '750 ml', orderIndex: 1 },
      { name: 'Lardons (bacon)', quantity: '150 g', orderIndex: 2 },
      { name: 'Pearl onions', quantity: '200 g', orderIndex: 3 },
      { name: 'Button mushrooms', quantity: '300 g', orderIndex: 4 },
      { name: 'Carrots', quantity: '2', orderIndex: 5 },
      { name: 'Beef stock', quantity: '300 ml', orderIndex: 6 },
      { name: 'Tomato paste', quantity: '1 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Marinate beef in wine with carrots and herbs overnight. Drain, reserving the marinade. Pat beef dry and brown in batches in a Dutch oven.', orderIndex: 0 },
      { stepText: 'Fry lardons until crisp. Add tomato paste and cook 1 minute. Pour in reserved marinade and stock. Return beef to pot.', orderIndex: 1 },
      { stepText: 'Bring to a simmer, cover, and braise in a 160�C (325�F) oven for 2.5�3 hours until beef is very tender.', orderIndex: 2 },
      { stepText: 'Saut� pearl onions and mushrooms separately in butter until golden. Add to the stew for the last 30 minutes of cooking. Adjust seasoning and serve with egg noodles or mashed potatoes.', orderIndex: 3 },
    ],
  },
  {
    title: 'Cr�pes Suzette',
    description: 'Delicate French cr�pes flamb�ed in a fragrant orange-butter sauce with Grand Marnier � a timeless classic.',
    category: 'Dessert',
    difficulty: 'Medium',
    preparationTimeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800',
    authorEmail: 'julia@recipenest.com',
    ingredients: [
      { name: 'Plain flour', quantity: '125 g', orderIndex: 0 },
      { name: 'Eggs', quantity: '3', orderIndex: 1 },
      { name: 'Whole milk', quantity: '300 ml', orderIndex: 2 },
      { name: 'Unsalted butter', quantity: '80 g', orderIndex: 3 },
      { name: 'Orange juice', quantity: '150 ml', orderIndex: 4 },
      { name: 'Orange zest', quantity: '1 orange', orderIndex: 5 },
      { name: 'Grand Marnier', quantity: '60 ml', orderIndex: 6 },
      { name: 'Caster sugar', quantity: '3 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Whisk flour, eggs, and milk into a smooth batter. Rest for 30 minutes. Cook thin cr�pes in a buttered pan, stacking them as you go.', orderIndex: 0 },
      { stepText: 'In a wide pan, melt butter with sugar until golden. Add orange juice and zest, stirring to form a sauce.', orderIndex: 1 },
      { stepText: 'Fold cr�pes into quarters and warm them in the orange sauce, turning to coat.', orderIndex: 2 },
      { stepText: 'Add Grand Marnier to the pan and carefully tilt to flamb� (or use a lighter). Let the flames die down and serve immediately.', orderIndex: 3 },
    ],
  },
  {
    title: 'Quiche Lorraine',
    description: 'A buttery, flaky pastry shell filled with a silky custard of eggs, cream, bacon, and Gruy�re � the definitive quiche.',
    category: 'Lunch',
    difficulty: 'Medium',
    preparationTimeMinutes: 75,
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800',
    authorEmail: 'julia@recipenest.com',
    ingredients: [
      { name: 'Shortcrust pastry', quantity: '300 g', orderIndex: 0 },
      { name: 'Smoked lardons', quantity: '150 g', orderIndex: 1 },
      { name: 'Eggs', quantity: '4', orderIndex: 2 },
      { name: 'Double cream', quantity: '300 ml', orderIndex: 3 },
      { name: 'Gruy�re, grated', quantity: '100 g', orderIndex: 4 },
      { name: 'Nutmeg', quantity: 'pinch', orderIndex: 5 },
      { name: 'Salt and white pepper', quantity: 'to taste', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Roll out pastry and line a 23 cm tart tin. Blind bake at 190�C (375�F) for 15 minutes with baking beans, then 5 minutes uncovered.', orderIndex: 0 },
      { stepText: 'Fry lardons until golden. Scatter over the pastry base along with the Gruy�re.', orderIndex: 1 },
      { stepText: 'Whisk eggs, cream, nutmeg, salt, and pepper. Pour over the filling.', orderIndex: 2 },
      { stepText: 'Bake at 180�C (350�F) for 30�35 minutes until just set with a slight wobble in the centre. Cool for 10 minutes before slicing.', orderIndex: 3 },
    ],
  },
  {
    title: 'Chocolate Mousse',
    description: 'An airy, intensely chocolatey mousse made the classic French way � no cream, just eggs, chocolate, and butter.',
    category: 'Dessert',
    difficulty: 'Medium',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1511715282680-fbf93a50e721?w=800',
    authorEmail: 'julia@recipenest.com',
    ingredients: [
      { name: 'Dark chocolate (70%)', quantity: '200 g', orderIndex: 0 },
      { name: 'Unsalted butter', quantity: '50 g', orderIndex: 1 },
      { name: 'Eggs, separated', quantity: '4', orderIndex: 2 },
      { name: 'Caster sugar', quantity: '60 g', orderIndex: 3 },
      { name: 'Strong espresso', quantity: '2 tbsp', orderIndex: 4 },
      { name: 'Pinch of salt', quantity: '1 pinch', orderIndex: 5 },
    ],
    instructions: [
      { stepText: 'Melt chocolate and butter together in a bowl over simmering water. Stir in espresso and let cool slightly.', orderIndex: 0 },
      { stepText: 'Whisk egg yolks with half the sugar until pale and thick. Fold into the chocolate mixture.', orderIndex: 1 },
      { stepText: 'Whisk egg whites with a pinch of salt to soft peaks. Gradually add remaining sugar and whisk to stiff peaks.', orderIndex: 2 },
      { stepText: 'Fold egg whites into the chocolate mixture in three additions, keeping as much air as possible. Spoon into glasses and refrigerate for at least 2 hours before serving.', orderIndex: 3 },
    ],
  },
  // -- Jamie Oliver (5 recipes) -----------------------------------------------
  {
    title: 'Spaghetti Carbonara',
    description: 'Jamie\'s authentic Roman carbonara � silky egg and Pecorino sauce clinging to al dente spaghetti with crispy guanciale.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    authorEmail: 'jamie@recipenest.com',
    ingredients: [
      { name: 'Spaghetti', quantity: '400 g', orderIndex: 0 },
      { name: 'Guanciale or pancetta', quantity: '150 g', orderIndex: 1 },
      { name: 'Egg yolks', quantity: '4', orderIndex: 2 },
      { name: 'Whole egg', quantity: '1', orderIndex: 3 },
      { name: 'Pecorino Romano, grated', quantity: '80 g', orderIndex: 4 },
      { name: 'Parmesan, grated', quantity: '40 g', orderIndex: 5 },
      { name: 'Black pepper, coarsely ground', quantity: '2 tsp', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Cook spaghetti in well-salted boiling water until al dente. Reserve 200 ml pasta water before draining.', orderIndex: 0 },
      { stepText: 'Fry guanciale in a dry pan over medium heat until crispy and the fat has rendered. Remove from heat.', orderIndex: 1 },
      { stepText: 'Whisk egg yolks, whole egg, Pecorino, Parmesan, and black pepper together in a bowl.', orderIndex: 2 },
      { stepText: 'Add hot drained pasta to the guanciale pan (off heat). Pour in egg mixture and toss vigorously, adding pasta water a splash at a time until you have a glossy, creamy sauce. Serve immediately.', orderIndex: 3 },
    ],
  },
  {
    title: 'Avocado Toast with Poached Eggs',
    description: 'Smashed avocado on sourdough with perfectly poached eggs, chilli flakes, and a squeeze of lemon.',
    category: 'Breakfast',
    difficulty: 'Easy',
    preparationTimeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=800',
    authorEmail: 'jamie@recipenest.com',
    ingredients: [
      { name: 'Sourdough bread', quantity: '2 thick slices', orderIndex: 0 },
      { name: 'Ripe avocados', quantity: '2', orderIndex: 1 },
      { name: 'Eggs', quantity: '2', orderIndex: 2 },
      { name: 'Lemon', quantity: '1/2', orderIndex: 3 },
      { name: 'Chilli flakes', quantity: '1/2 tsp', orderIndex: 4 },
      { name: 'White wine vinegar', quantity: '1 tbsp', orderIndex: 5 },
      { name: 'Extra virgin olive oil', quantity: '1 tbsp', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Toast sourdough until golden and crisp.', orderIndex: 0 },
      { stepText: 'Halve and pit avocados. Scoop flesh into a bowl, add lemon juice, salt, and pepper. Smash roughly with a fork � keep it chunky.', orderIndex: 1 },
      { stepText: 'Bring a pan of water to a gentle simmer. Add vinegar. Crack each egg into a cup and slide into the water. Poach for 3 minutes for a runny yolk.', orderIndex: 2 },
      { stepText: 'Pile smashed avocado onto toast, top with a poached egg, drizzle with olive oil, and scatter chilli flakes. Season and serve.', orderIndex: 3 },
    ],
  },
  {
    title: 'Chicken Stir-Fry',
    description: 'A quick, vibrant stir-fry with tender chicken, colourful vegetables, and a punchy ginger-soy sauce.',
    category: 'Dinner',
    difficulty: 'Easy',
    preparationTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    authorEmail: 'jamie@recipenest.com',
    ingredients: [
      { name: 'Chicken breast, sliced', quantity: '500 g', orderIndex: 0 },
      { name: 'Mixed peppers', quantity: '2', orderIndex: 1 },
      { name: 'Broccoli florets', quantity: '200 g', orderIndex: 2 },
      { name: 'Soy sauce', quantity: '3 tbsp', orderIndex: 3 },
      { name: 'Fresh ginger', quantity: '2 cm piece', orderIndex: 4 },
      { name: 'Garlic cloves', quantity: '3', orderIndex: 5 },
      { name: 'Sesame oil', quantity: '1 tbsp', orderIndex: 6 },
      { name: 'Cornflour', quantity: '1 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Toss chicken slices with cornflour, salt, and pepper. Mix soy sauce, grated ginger, and minced garlic in a small bowl.', orderIndex: 0 },
      { stepText: 'Heat a wok over the highest heat until smoking. Add oil and stir-fry chicken for 3�4 minutes until golden. Remove.', orderIndex: 1 },
      { stepText: 'Add peppers and broccoli to the wok. Stir-fry for 3 minutes until just tender but still crisp.', orderIndex: 2 },
      { stepText: 'Return chicken to the wok, pour in the sauce, and toss everything together for 1 minute. Finish with sesame oil and serve over steamed rice.', orderIndex: 3 },
    ],
  },
  {
    title: 'Homemade Margherita Pizza',
    description: 'A thin, crispy pizza with a simple tomato sauce, fresh mozzarella, and fragrant basil � Neapolitan style at home.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    authorEmail: 'jamie@recipenest.com',
    ingredients: [
      { name: 'Strong bread flour', quantity: '500 g', orderIndex: 0 },
      { name: 'Instant yeast', quantity: '7 g', orderIndex: 1 },
      { name: 'Canned San Marzano tomatoes', quantity: '400 g', orderIndex: 2 },
      { name: 'Fresh mozzarella', quantity: '250 g', orderIndex: 3 },
      { name: 'Fresh basil', quantity: 'handful', orderIndex: 4 },
      { name: 'Extra virgin olive oil', quantity: '3 tbsp', orderIndex: 5 },
      { name: 'Salt', quantity: '1 tsp', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Mix flour, yeast, salt, and 320 ml warm water into a dough. Knead for 10 minutes until smooth and elastic. Cover and prove for 1 hour.', orderIndex: 0 },
      { stepText: 'Crush tomatoes by hand, season with salt and a drizzle of olive oil. Do not cook � this is the sauce.', orderIndex: 1 },
      { stepText: 'Preheat oven to its maximum temperature (250�C+) with a baking stone or heavy tray inside. Stretch dough into a thin round.', orderIndex: 2 },
      { stepText: 'Spread tomato sauce, tear over mozzarella, and bake for 8�10 minutes until the crust is charred at the edges. Top with fresh basil and a drizzle of olive oil.', orderIndex: 3 },
    ],
  },
  {
    title: 'Grilled Chicken with Herb Salad',
    description: 'Juicy marinated grilled chicken served over a bright, herby salad with lemon dressing.',
    category: 'Lunch',
    difficulty: 'Easy',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    authorEmail: 'jamie@recipenest.com',
    ingredients: [
      { name: 'Chicken thighs, boneless', quantity: '4', orderIndex: 0 },
      { name: 'Mixed salad leaves', quantity: '100 g', orderIndex: 1 },
      { name: 'Fresh parsley', quantity: 'handful', orderIndex: 2 },
      { name: 'Fresh mint', quantity: 'handful', orderIndex: 3 },
      { name: 'Lemon', quantity: '1', orderIndex: 4 },
      { name: 'Olive oil', quantity: '4 tbsp', orderIndex: 5 },
      { name: 'Garlic', quantity: '2 cloves', orderIndex: 6 },
      { name: 'Smoked paprika', quantity: '1 tsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Marinate chicken in olive oil, minced garlic, paprika, lemon zest, salt, and pepper for at least 15 minutes.', orderIndex: 0 },
      { stepText: 'Grill chicken on a hot griddle pan for 5�6 minutes per side until cooked through and nicely charred.', orderIndex: 1 },
      { stepText: 'Toss salad leaves, parsley, and mint with lemon juice, olive oil, salt, and pepper.', orderIndex: 2 },
      { stepText: 'Slice chicken and serve over the herb salad. Squeeze extra lemon over the top.', orderIndex: 3 },
    ],
  },
  // -- Yotam Ottolenghi (5 recipes) ------------------------------------------
  {
    title: 'Roasted Cauliflower with Tahini',
    description: 'Whole roasted cauliflower with a golden crust, drizzled with lemon tahini and scattered with pomegranate seeds and herbs.',
    category: 'Dinner',
    difficulty: 'Easy',
    preparationTimeMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    authorEmail: 'yotam@recipenest.com',
    ingredients: [
      { name: 'Cauliflower', quantity: '1 large head', orderIndex: 0 },
      { name: 'Tahini', quantity: '4 tbsp', orderIndex: 1 },
      { name: 'Lemon juice', quantity: '3 tbsp', orderIndex: 2 },
      { name: 'Pomegranate seeds', quantity: '4 tbsp', orderIndex: 3 },
      { name: 'Fresh parsley', quantity: 'handful', orderIndex: 4 },
      { name: 'Olive oil', quantity: '4 tbsp', orderIndex: 5 },
      { name: 'Cumin seeds', quantity: '1 tsp', orderIndex: 6 },
      { name: 'Garlic clove', quantity: '1', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Preheat oven to 220�C (425�F). Rub cauliflower all over with olive oil, cumin, salt, and pepper. Place on a baking tray.', orderIndex: 0 },
      { stepText: 'Roast for 40�45 minutes, turning once, until deeply golden and tender throughout.', orderIndex: 1 },
      { stepText: 'Whisk tahini with lemon juice, crushed garlic, and 3�4 tbsp water until smooth and pourable. Season.', orderIndex: 2 },
      { stepText: 'Place cauliflower on a platter, drizzle generously with tahini sauce, and scatter pomegranate seeds and parsley over the top.', orderIndex: 3 },
    ],
  },
  {
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce � a vibrant Middle Eastern breakfast that works any time of day.',
    category: 'Breakfast',
    difficulty: 'Easy',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    authorEmail: 'yotam@recipenest.com',
    ingredients: [
      { name: 'Eggs', quantity: '6', orderIndex: 0 },
      { name: 'Canned chopped tomatoes', quantity: '800 g', orderIndex: 1 },
      { name: 'Red peppers', quantity: '2', orderIndex: 2 },
      { name: 'Onion', quantity: '1', orderIndex: 3 },
      { name: 'Garlic cloves', quantity: '4', orderIndex: 4 },
      { name: 'Cumin', quantity: '1 tsp', orderIndex: 5 },
      { name: 'Smoked paprika', quantity: '1 tsp', orderIndex: 6 },
      { name: 'Feta cheese', quantity: '80 g', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Saut� diced onion and sliced peppers in olive oil for 8 minutes until soft. Add garlic, cumin, and paprika; cook 1 minute.', orderIndex: 0 },
      { stepText: 'Pour in tomatoes, season, and simmer for 15 minutes until the sauce thickens.', orderIndex: 1 },
      { stepText: 'Make 6 wells in the sauce. Crack an egg into each well. Cover and cook over low heat for 5�7 minutes until whites are set but yolks are still runny.', orderIndex: 2 },
      { stepText: 'Crumble feta over the top and serve straight from the pan with warm flatbread.', orderIndex: 3 },
    ],
  },
  {
    title: 'Lamb Kofta with Yoghurt Sauce',
    description: 'Spiced lamb kofta skewers served with a cool, garlicky yoghurt sauce and warm flatbreads.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 40,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    authorEmail: 'yotam@recipenest.com',
    ingredients: [
      { name: 'Minced lamb', quantity: '600 g', orderIndex: 0 },
      { name: 'Onion, grated', quantity: '1', orderIndex: 1 },
      { name: 'Ground cumin', quantity: '1.5 tsp', orderIndex: 2 },
      { name: 'Ground coriander', quantity: '1 tsp', orderIndex: 3 },
      { name: 'Cinnamon', quantity: '1/2 tsp', orderIndex: 4 },
      { name: 'Greek yoghurt', quantity: '200 g', orderIndex: 5 },
      { name: 'Garlic clove', quantity: '1', orderIndex: 6 },
      { name: 'Fresh mint', quantity: '2 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Combine lamb, grated onion, cumin, coriander, cinnamon, salt, and pepper. Mix well and shape around skewers into elongated sausages.', orderIndex: 0 },
      { stepText: 'Refrigerate for 20 minutes to firm up.', orderIndex: 1 },
      { stepText: 'Grill kofta on a hot griddle or barbecue for 3�4 minutes per side until cooked through and charred.', orderIndex: 2 },
      { stepText: 'Mix yoghurt with crushed garlic, chopped mint, lemon juice, and salt. Serve kofta with yoghurt sauce and warm flatbreads.', orderIndex: 3 },
    ],
  },
  {
    title: 'Roasted Vegetable Salad',
    description: 'A colourful salad of roasted seasonal vegetables with a pomegranate molasses dressing and toasted pine nuts.',
    category: 'Salad',
    difficulty: 'Easy',
    preparationTimeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    authorEmail: 'yotam@recipenest.com',
    ingredients: [
      { name: 'Courgettes', quantity: '2', orderIndex: 0 },
      { name: 'Red onions', quantity: '2', orderIndex: 1 },
      { name: 'Cherry tomatoes', quantity: '200 g', orderIndex: 2 },
      { name: 'Aubergine', quantity: '1', orderIndex: 3 },
      { name: 'Pomegranate molasses', quantity: '2 tbsp', orderIndex: 4 },
      { name: 'Pine nuts, toasted', quantity: '3 tbsp', orderIndex: 5 },
      { name: 'Fresh basil', quantity: 'handful', orderIndex: 6 },
      { name: 'Olive oil', quantity: '4 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Cut all vegetables into chunks. Toss with olive oil, salt, and pepper. Spread on baking trays in a single layer.', orderIndex: 0 },
      { stepText: 'Roast at 220�C (425�F) for 30�35 minutes until caramelised and tender.', orderIndex: 1 },
      { stepText: 'Whisk pomegranate molasses with olive oil, a pinch of salt, and a splash of water.', orderIndex: 2 },
      { stepText: 'Arrange roasted vegetables on a platter. Drizzle with dressing, scatter pine nuts and basil, and serve warm or at room temperature.', orderIndex: 3 },
    ],
  },
  {
    title: 'Spiced Lentil Soup',
    description: 'A warming, deeply spiced red lentil soup with crispy cumin-butter drizzled on top.',
    category: 'Soup',
    difficulty: 'Easy',
    preparationTimeMinutes: 40,
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
    authorEmail: 'yotam@recipenest.com',
    ingredients: [
      { name: 'Red lentils', quantity: '300 g', orderIndex: 0 },
      { name: 'Onion', quantity: '1 large', orderIndex: 1 },
      { name: 'Garlic cloves', quantity: '4', orderIndex: 2 },
      { name: 'Ground cumin', quantity: '2 tsp', orderIndex: 3 },
      { name: 'Turmeric', quantity: '1 tsp', orderIndex: 4 },
      { name: 'Vegetable stock', quantity: '1.2 litres', orderIndex: 5 },
      { name: 'Lemon juice', quantity: '2 tbsp', orderIndex: 6 },
      { name: 'Butter', quantity: '30 g', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Saut� diced onion in olive oil for 8 minutes. Add garlic, cumin, and turmeric; cook 1 minute.', orderIndex: 0 },
      { stepText: 'Add rinsed lentils and stock. Bring to a boil, then simmer for 20 minutes until lentils are completely soft.', orderIndex: 1 },
      { stepText: 'Blend until smooth. Stir in lemon juice and season generously.', orderIndex: 2 },
      { stepText: 'Melt butter in a small pan, add a pinch of cumin, and let it sizzle for 30 seconds. Ladle soup into bowls and drizzle the spiced butter over the top.', orderIndex: 3 },
    ],
  },
  // -- Nigella Lawson (5 recipes) ---------------------------------------------
  {
    title: 'Chocolate Fudge Cake',
    description: 'Nigella\'s legendary chocolate fudge cake � deeply dark, moist, and covered in a glossy ganache frosting.',
    category: 'Dessert',
    difficulty: 'Medium',
    preparationTimeMinutes: 75,
    imageUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800',
    authorEmail: 'nigella@recipenest.com',
    ingredients: [
      { name: 'Plain flour', quantity: '225 g', orderIndex: 0 },
      { name: 'Caster sugar', quantity: '300 g', orderIndex: 1 },
      { name: 'Cocoa powder', quantity: '50 g', orderIndex: 2 },
      { name: 'Eggs', quantity: '2', orderIndex: 3 },
      { name: 'Buttermilk', quantity: '250 ml', orderIndex: 4 },
      { name: 'Unsalted butter', quantity: '175 g', orderIndex: 5 },
      { name: 'Dark chocolate (70%)', quantity: '200 g', orderIndex: 6 },
      { name: 'Double cream', quantity: '150 ml', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Preheat oven to 180�C (350�F). Grease and line two 20 cm cake tins. Melt butter and 100 g chocolate together; cool slightly.', orderIndex: 0 },
      { stepText: 'Whisk sugar, eggs, and buttermilk into the chocolate mixture. Sift in flour and cocoa; fold until smooth.', orderIndex: 1 },
      { stepText: 'Divide between tins and bake for 30�35 minutes. Cool completely on a wire rack.', orderIndex: 2 },
      { stepText: 'Heat cream until just simmering. Pour over remaining chopped chocolate; stir until glossy. Cool until spreadable. Sandwich and frost the cake with the ganache.', orderIndex: 3 },
    ],
  },
  {
    title: 'Banana Bread',
    description: 'The most comforting banana bread � dense, moist, and fragrant with vanilla and a hint of cinnamon.',
    category: 'Breakfast',
    difficulty: 'Easy',
    preparationTimeMinutes: 75,
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800',
    authorEmail: 'nigella@recipenest.com',
    ingredients: [
      { name: 'Very ripe bananas', quantity: '3 large', orderIndex: 0 },
      { name: 'Plain flour', quantity: '225 g', orderIndex: 1 },
      { name: 'Caster sugar', quantity: '150 g', orderIndex: 2 },
      { name: 'Eggs', quantity: '2', orderIndex: 3 },
      { name: 'Unsalted butter, melted', quantity: '100 g', orderIndex: 4 },
      { name: 'Vanilla extract', quantity: '1 tsp', orderIndex: 5 },
      { name: 'Cinnamon', quantity: '1 tsp', orderIndex: 6 },
      { name: 'Baking soda', quantity: '1 tsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Preheat oven to 170�C (340�F). Grease a 900 g loaf tin. Mash bananas thoroughly in a large bowl.', orderIndex: 0 },
      { stepText: 'Stir in melted butter, sugar, eggs, and vanilla until combined.', orderIndex: 1 },
      { stepText: 'Fold in flour, baking soda, cinnamon, and a pinch of salt until just combined � do not overmix.', orderIndex: 2 },
      { stepText: 'Pour into the tin and bake for 55�65 minutes until a skewer comes out clean. Cool in the tin for 10 minutes before turning out.', orderIndex: 3 },
    ],
  },
  {
    title: 'Pasta e Fagioli',
    description: 'A rustic Italian pasta and bean soup � thick, hearty, and deeply satisfying with rosemary and Parmesan.',
    category: 'Soup',
    difficulty: 'Easy',
    preparationTimeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800',
    authorEmail: 'nigella@recipenest.com',
    ingredients: [
      { name: 'Cannellini beans (canned)', quantity: '2 x 400 g tins', orderIndex: 0 },
      { name: 'Ditalini pasta', quantity: '150 g', orderIndex: 1 },
      { name: 'Pancetta', quantity: '100 g', orderIndex: 2 },
      { name: 'Garlic cloves', quantity: '3', orderIndex: 3 },
      { name: 'Rosemary sprig', quantity: '1', orderIndex: 4 },
      { name: 'Chicken stock', quantity: '800 ml', orderIndex: 5 },
      { name: 'Parmesan rind', quantity: '1 piece', orderIndex: 6 },
      { name: 'Olive oil', quantity: '3 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Fry pancetta in olive oil until crisp. Add garlic and rosemary; cook 1 minute.', orderIndex: 0 },
      { stepText: 'Add beans (with their liquid), stock, and Parmesan rind. Simmer for 15 minutes.', orderIndex: 1 },
      { stepText: 'Remove half the beans and blend until smooth. Return to the pot to create a thick, creamy base.', orderIndex: 2 },
      { stepText: 'Add pasta and cook until al dente. Remove Parmesan rind. Serve with a drizzle of olive oil and grated Parmesan.', orderIndex: 3 },
    ],
  },
  {
    title: 'Cheesecake with Berry Compote',
    description: 'A no-bake vanilla cheesecake with a buttery biscuit base and a vibrant mixed berry compote.',
    category: 'Dessert',
    difficulty: 'Easy',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91798d047e?w=800',
    authorEmail: 'nigella@recipenest.com',
    ingredients: [
      { name: 'Digestive biscuits', quantity: '250 g', orderIndex: 0 },
      { name: 'Unsalted butter, melted', quantity: '100 g', orderIndex: 1 },
      { name: 'Full-fat cream cheese', quantity: '600 g', orderIndex: 2 },
      { name: 'Icing sugar', quantity: '100 g', orderIndex: 3 },
      { name: 'Double cream', quantity: '200 ml', orderIndex: 4 },
      { name: 'Vanilla extract', quantity: '1 tsp', orderIndex: 5 },
      { name: 'Mixed berries (frozen)', quantity: '300 g', orderIndex: 6 },
      { name: 'Caster sugar', quantity: '3 tbsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Crush biscuits and mix with melted butter. Press firmly into the base of a 23 cm springform tin. Refrigerate for 30 minutes.', orderIndex: 0 },
      { stepText: 'Beat cream cheese with icing sugar and vanilla until smooth. Whip cream to soft peaks and fold into the cream cheese mixture.', orderIndex: 1 },
      { stepText: 'Spread filling over the biscuit base. Smooth the top and refrigerate for at least 4 hours (overnight is best).', orderIndex: 2 },
      { stepText: 'Simmer berries with caster sugar for 10 minutes until jammy. Cool. Spoon over the cheesecake just before serving.', orderIndex: 3 },
    ],
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Tender marinated chicken in a rich, creamy tomato and spice sauce � Britain\'s most beloved curry.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800',
    authorEmail: 'nigella@recipenest.com',
    ingredients: [
      { name: 'Chicken thighs, cubed', quantity: '700 g', orderIndex: 0 },
      { name: 'Greek yoghurt', quantity: '150 g', orderIndex: 1 },
      { name: 'Garam masala', quantity: '2 tsp', orderIndex: 2 },
      { name: 'Canned tomatoes', quantity: '400 g', orderIndex: 3 },
      { name: 'Double cream', quantity: '150 ml', orderIndex: 4 },
      { name: 'Onion', quantity: '1 large', orderIndex: 5 },
      { name: 'Garlic and ginger paste', quantity: '2 tbsp', orderIndex: 6 },
      { name: 'Ground cumin', quantity: '1 tsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Marinate chicken in yoghurt, garam masala, and salt for at least 30 minutes. Grill or pan-fry until charred. Set aside.', orderIndex: 0 },
      { stepText: 'Saut� onion in oil for 10 minutes until golden. Add garlic-ginger paste and cumin; cook 2 minutes.', orderIndex: 1 },
      { stepText: 'Add tomatoes and simmer for 15 minutes until the sauce thickens. Blend until smooth.', orderIndex: 2 },
      { stepText: 'Return sauce to the pan, add cream and chicken. Simmer for 10 minutes. Serve with basmati rice and naan.', orderIndex: 3 },
    ],
  },
  // -- Thomas Keller (5 recipes) ----------------------------------------------
  {
    title: 'Roast Chicken with Herbs',
    description: 'Thomas Keller\'s legendary simple roast chicken � perfectly crispy skin, juicy meat, and nothing but salt, pepper, and thyme.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800',
    authorEmail: 'thomas@recipenest.com',
    ingredients: [
      { name: 'Whole chicken', quantity: '1.5 kg', orderIndex: 0 },
      { name: 'Kosher salt', quantity: '2 tbsp', orderIndex: 1 },
      { name: 'Black pepper', quantity: '1 tsp', orderIndex: 2 },
      { name: 'Fresh thyme', quantity: '6 sprigs', orderIndex: 3 },
      { name: 'Garlic head', quantity: '1', orderIndex: 4 },
      { name: 'Unsalted butter', quantity: '30 g', orderIndex: 5 },
      { name: 'Lemon', quantity: '1', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Pat chicken completely dry inside and out. Season generously with salt and pepper all over, including the cavity. Leave uncovered in the fridge for at least 1 hour (overnight is ideal).', orderIndex: 0 },
      { stepText: 'Preheat oven to 230�C (450�F). Stuff the cavity with thyme, halved garlic head, and lemon halves. Truss the chicken tightly.', orderIndex: 1 },
      { stepText: 'Place in a roasting pan and roast for 50�60 minutes until the skin is deep golden and the juices run clear.', orderIndex: 2 },
      { stepText: 'Rest for 15 minutes before carving. Baste with the pan juices and serve with the roasted garlic squeezed out alongside.', orderIndex: 3 },
    ],
  },
  {
    title: 'Lobster Bisque',
    description: 'A velvety, intensely flavoured lobster bisque with a touch of brandy and cream � the pinnacle of French seafood soups.',
    category: 'Soup',
    difficulty: 'Hard',
    preparationTimeMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
    authorEmail: 'thomas@recipenest.com',
    ingredients: [
      { name: 'Lobster tails', quantity: '2', orderIndex: 0 },
      { name: 'Lobster shells', quantity: 'from 2 lobsters', orderIndex: 1 },
      { name: 'Double cream', quantity: '300 ml', orderIndex: 2 },
      { name: 'Brandy', quantity: '60 ml', orderIndex: 3 },
      { name: 'Onion', quantity: '1', orderIndex: 4 },
      { name: 'Celery stalks', quantity: '2', orderIndex: 5 },
      { name: 'Tomato paste', quantity: '2 tbsp', orderIndex: 6 },
      { name: 'Fish stock', quantity: '1 litre', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Roast lobster shells in a hot oven for 15 minutes. Saut� onion and celery in butter until soft. Add shells and tomato paste; cook 3 minutes.', orderIndex: 0 },
      { stepText: 'Add brandy and flamb�. Pour in fish stock and simmer for 30 minutes. Strain through a fine sieve, pressing hard on the shells.', orderIndex: 1 },
      { stepText: 'Return strained stock to the pan. Add cream and simmer until reduced by a third and slightly thickened.', orderIndex: 2 },
      { stepText: 'Poach lobster tails in the bisque for 4�5 minutes. Remove, slice, and serve in the bisque with a swirl of cream.', orderIndex: 3 },
    ],
  },
  {
    title: 'Eggs Benedict',
    description: 'Classic eggs Benedict with Canadian bacon, perfectly poached eggs, and a rich, buttery hollandaise sauce.',
    category: 'Breakfast',
    difficulty: 'Hard',
    preparationTimeMinutes: 35,
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800',
    authorEmail: 'thomas@recipenest.com',
    ingredients: [
      { name: 'English muffins', quantity: '2', orderIndex: 0 },
      { name: 'Canadian bacon slices', quantity: '4', orderIndex: 1 },
      { name: 'Eggs', quantity: '4', orderIndex: 2 },
      { name: 'Egg yolks', quantity: '3', orderIndex: 3 },
      { name: 'Unsalted butter, clarified', quantity: '150 g', orderIndex: 4 },
      { name: 'Lemon juice', quantity: '1 tbsp', orderIndex: 5 },
      { name: 'White wine vinegar', quantity: '1 tbsp', orderIndex: 6 },
      { name: 'Cayenne pepper', quantity: 'pinch', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Make hollandaise: whisk egg yolks with lemon juice in a bowl over simmering water until thick and pale. Slowly drizzle in warm clarified butter, whisking constantly. Season with cayenne and salt.', orderIndex: 0 },
      { stepText: 'Toast muffin halves. Pan-fry Canadian bacon until lightly browned.', orderIndex: 1 },
      { stepText: 'Poach eggs in simmering water with vinegar for 3 minutes. Remove with a slotted spoon and drain.', orderIndex: 2 },
      { stepText: 'Assemble: muffin, bacon, poached egg, generous hollandaise. Serve immediately.', orderIndex: 3 },
    ],
  },
  {
    title: 'Steak Frites',
    description: 'A perfectly cooked ribeye steak with crispy double-fried French fries and a classic b�arnaise sauce.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=800',
    authorEmail: 'thomas@recipenest.com',
    ingredients: [
      { name: 'Ribeye steak', quantity: '2 x 300 g', orderIndex: 0 },
      { name: 'Russet potatoes', quantity: '4 large', orderIndex: 1 },
      { name: 'Vegetable oil for frying', quantity: '1 litre', orderIndex: 2 },
      { name: 'Unsalted butter', quantity: '50 g', orderIndex: 3 },
      { name: 'Garlic cloves', quantity: '3', orderIndex: 4 },
      { name: 'Fresh thyme', quantity: '3 sprigs', orderIndex: 5 },
      { name: 'Fleur de sel', quantity: 'to taste', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Cut potatoes into fries. Fry at 150�C (300�F) for 5 minutes (blanch). Drain and cool. This can be done ahead.', orderIndex: 0 },
      { stepText: 'Season steaks generously. Sear in a very hot cast-iron pan for 3 minutes per side. Add butter, garlic, and thyme; baste for 1 minute. Rest for 5 minutes.', orderIndex: 1 },
      { stepText: 'Fry the blanched potatoes again at 190�C (375�F) for 3�4 minutes until golden and crispy. Drain and season immediately with fleur de sel.', orderIndex: 2 },
      { stepText: 'Slice steak against the grain and serve alongside the frites with b�arnaise sauce.', orderIndex: 3 },
    ],
  },
  {
    title: 'Cr�me Br�l�e',
    description: 'A silky vanilla custard with a perfectly caramelised sugar crust � the most satisfying crack in all of desserts.',
    category: 'Dessert',
    difficulty: 'Medium',
    preparationTimeMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
    authorEmail: 'thomas@recipenest.com',
    ingredients: [
      { name: 'Double cream', quantity: '500 ml', orderIndex: 0 },
      { name: 'Egg yolks', quantity: '6', orderIndex: 1 },
      { name: 'Caster sugar', quantity: '100 g', orderIndex: 2 },
      { name: 'Vanilla pod', quantity: '1', orderIndex: 3 },
      { name: 'Demerara sugar (for topping)', quantity: '4 tbsp', orderIndex: 4 },
    ],
    instructions: [
      { stepText: 'Heat cream with split vanilla pod until just simmering. Whisk egg yolks with caster sugar until pale. Slowly pour hot cream into yolks, whisking constantly.', orderIndex: 0 },
      { stepText: 'Strain through a fine sieve. Skim off any foam. Pour into 4 ramekins.', orderIndex: 1 },
      { stepText: 'Bake in a bain-marie at 150�C (300�F) for 35�40 minutes until just set with a slight wobble. Cool, then refrigerate for at least 2 hours.', orderIndex: 2 },
      { stepText: 'Sprinkle demerara sugar evenly over each custard. Caramelise with a blowtorch until golden and glassy. Serve immediately.', orderIndex: 3 },
    ],
  },
  // -- Ina Garten (5 recipes) -------------------------------------------------
  {
    title: 'Ina\'s Roasted Tomato Soup',
    description: 'Slow-roasted tomatoes blended into a velvety, deeply flavoured soup with fresh basil and a swirl of cream.',
    category: 'Soup',
    difficulty: 'Easy',
    preparationTimeMinutes: 75,
    imageUrl: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800',
    authorEmail: 'ina@recipenest.com',
    ingredients: [
      { name: 'Plum tomatoes', quantity: '1.5 kg', orderIndex: 0 },
      { name: 'Onion', quantity: '1 large', orderIndex: 1 },
      { name: 'Garlic cloves', quantity: '6', orderIndex: 2 },
      { name: 'Chicken stock', quantity: '500 ml', orderIndex: 3 },
      { name: 'Fresh basil', quantity: 'large handful', orderIndex: 4 },
      { name: 'Double cream', quantity: '100 ml', orderIndex: 5 },
      { name: 'Olive oil', quantity: '4 tbsp', orderIndex: 6 },
      { name: 'Sugar', quantity: '1 tsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Halve tomatoes and place cut-side up on a baking tray with onion wedges and garlic. Drizzle with olive oil, season, and roast at 200�C (400�F) for 45 minutes.', orderIndex: 0 },
      { stepText: 'Transfer roasted vegetables to a blender with stock and basil. Blend until smooth.', orderIndex: 1 },
      { stepText: 'Pass through a sieve for a silky texture. Return to a pan and heat through. Add sugar and adjust seasoning.', orderIndex: 2 },
      { stepText: 'Ladle into bowls and swirl in cream. Serve with crusty bread.', orderIndex: 3 },
    ],
  },
  {
    title: 'Lemon Bars',
    description: 'Buttery shortbread topped with a bright, tangy lemon curd filling and dusted with icing sugar.',
    category: 'Dessert',
    difficulty: 'Easy',
    preparationTimeMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
    authorEmail: 'ina@recipenest.com',
    ingredients: [
      { name: 'Plain flour', quantity: '225 g', orderIndex: 0 },
      { name: 'Icing sugar', quantity: '50 g', orderIndex: 1 },
      { name: 'Unsalted butter, cold', quantity: '175 g', orderIndex: 2 },
      { name: 'Eggs', quantity: '4', orderIndex: 3 },
      { name: 'Caster sugar', quantity: '350 g', orderIndex: 4 },
      { name: 'Lemon juice', quantity: '120 ml', orderIndex: 5 },
      { name: 'Lemon zest', quantity: '2 lemons', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Pulse flour, icing sugar, and cold butter in a food processor until it resembles breadcrumbs. Press into a lined 23x33 cm tin. Bake at 180�C (350�F) for 20 minutes until pale golden.', orderIndex: 0 },
      { stepText: 'Whisk eggs, caster sugar, lemon juice, and zest together.', orderIndex: 1 },
      { stepText: 'Pour lemon mixture over the hot crust and bake for a further 25 minutes until just set.', orderIndex: 2 },
      { stepText: 'Cool completely, then refrigerate for 1 hour. Dust generously with icing sugar and cut into bars.', orderIndex: 3 },
    ],
  },
  {
    title: 'Barefoot Contessa Pasta Salad',
    description: 'A vibrant pasta salad with sun-dried tomatoes, olives, feta, and a herby vinaigrette � perfect for entertaining.',
    category: 'Salad',
    difficulty: 'Easy',
    preparationTimeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
    authorEmail: 'ina@recipenest.com',
    ingredients: [
      { name: 'Fusilli pasta', quantity: '400 g', orderIndex: 0 },
      { name: 'Sun-dried tomatoes', quantity: '100 g', orderIndex: 1 },
      { name: 'Kalamata olives', quantity: '80 g', orderIndex: 2 },
      { name: 'Feta cheese', quantity: '150 g', orderIndex: 3 },
      { name: 'Fresh basil', quantity: 'large handful', orderIndex: 4 },
      { name: 'Red wine vinegar', quantity: '3 tbsp', orderIndex: 5 },
      { name: 'Olive oil', quantity: '5 tbsp', orderIndex: 6 },
      { name: 'Dijon mustard', quantity: '1 tsp', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Cook pasta in well-salted water until al dente. Drain and rinse under cold water. Toss with a little olive oil.', orderIndex: 0 },
      { stepText: 'Whisk vinegar, mustard, olive oil, salt, and pepper into a dressing.', orderIndex: 1 },
      { stepText: 'Combine pasta with sun-dried tomatoes, olives, and basil. Pour over dressing and toss well.', orderIndex: 2 },
      { stepText: 'Crumble feta over the top. Serve at room temperature or chilled.', orderIndex: 3 },
    ],
  },
  {
    title: 'Blueberry Pancakes',
    description: 'Fluffy, golden pancakes bursting with fresh blueberries � the perfect weekend breakfast.',
    category: 'Breakfast',
    difficulty: 'Easy',
    preparationTimeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    authorEmail: 'ina@recipenest.com',
    ingredients: [
      { name: 'Plain flour', quantity: '200 g', orderIndex: 0 },
      { name: 'Baking powder', quantity: '2 tsp', orderIndex: 1 },
      { name: 'Caster sugar', quantity: '2 tbsp', orderIndex: 2 },
      { name: 'Eggs', quantity: '2', orderIndex: 3 },
      { name: 'Whole milk', quantity: '300 ml', orderIndex: 4 },
      { name: 'Unsalted butter, melted', quantity: '50 g', orderIndex: 5 },
      { name: 'Fresh blueberries', quantity: '150 g', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Whisk flour, baking powder, sugar, and a pinch of salt in a bowl. Make a well in the centre.', orderIndex: 0 },
      { stepText: 'Beat eggs, milk, and melted butter together. Pour into the well and stir until just combined � lumps are fine.', orderIndex: 1 },
      { stepText: 'Heat a non-stick pan over medium heat. Melt a little butter. Pour in batter (about 80 ml per pancake) and scatter blueberries on top.', orderIndex: 2 },
      { stepText: 'Cook until bubbles form on the surface (2�3 minutes), then flip and cook 1�2 minutes more. Serve with maple syrup.', orderIndex: 3 },
    ],
  },
  {
    title: 'Roasted Salmon with Dill',
    description: 'A whole side of salmon roasted with lemon, dill, and capers � elegant, effortless, and perfect for a crowd.',
    category: 'Dinner',
    difficulty: 'Easy',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800',
    authorEmail: 'ina@recipenest.com',
    ingredients: [
      { name: 'Salmon side (skin-on)', quantity: '1.2 kg', orderIndex: 0 },
      { name: 'Fresh dill', quantity: 'large bunch', orderIndex: 1 },
      { name: 'Lemon', quantity: '2', orderIndex: 2 },
      { name: 'Capers', quantity: '2 tbsp', orderIndex: 3 },
      { name: 'Olive oil', quantity: '3 tbsp', orderIndex: 4 },
      { name: 'Dijon mustard', quantity: '2 tbsp', orderIndex: 5 },
      { name: 'Garlic cloves', quantity: '2', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Preheat oven to 200�C (400�F). Line a large baking tray with foil. Place salmon skin-side down.', orderIndex: 0 },
      { stepText: 'Mix mustard, olive oil, minced garlic, and lemon zest. Spread over the salmon. Scatter dill and capers on top. Lay lemon slices over.', orderIndex: 1 },
      { stepText: 'Roast for 15�18 minutes until the salmon is just cooked through and flakes easily.', orderIndex: 2 },
      { stepText: 'Serve directly from the tray with a green salad and crusty bread.', orderIndex: 3 },
    ],
  },
  // -- Heston Blumenthal (5 recipes) -----------------------------------------
  {
    title: 'Triple-Cooked Chips',
    description: 'Heston\'s legendary triple-cooked chips � the crunchiest exterior with a fluffy interior, achieved through a three-stage cooking process.',
    category: 'Snack',
    difficulty: 'Hard',
    preparationTimeMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    authorEmail: 'heston@recipenest.com',
    ingredients: [
      { name: 'Maris Piper potatoes', quantity: '1 kg', orderIndex: 0 },
      { name: 'Vegetable oil for frying', quantity: '2 litres', orderIndex: 1 },
      { name: 'Fleur de sel', quantity: 'to taste', orderIndex: 2 },
    ],
    instructions: [
      { stepText: 'Peel and cut potatoes into thick chips (2 cm). Rinse under cold water. Place in a pan of cold salted water, bring to a boil, and simmer for 15�20 minutes until just cooked but not falling apart. Drain carefully and cool on a wire rack.', orderIndex: 0 },
      { stepText: 'Freeze the chips for 1 hour (this draws out moisture). Fry in oil at 130�C (265�F) for 5 minutes. Drain and freeze again for 30 minutes.', orderIndex: 1 },
      { stepText: 'Fry at 190�C (375�F) for 7�8 minutes until deeply golden and shatteringly crisp.', orderIndex: 2 },
      { stepText: 'Drain on paper towels, season immediately with fleur de sel, and serve at once.', orderIndex: 3 },
    ],
  },
  {
    title: 'Slow-Cooked Pork Belly',
    description: 'Pork belly slow-cooked for 36 hours at low temperature, then crisped under a blazing grill � meltingly tender with crackling skin.',
    category: 'Dinner',
    difficulty: 'Hard',
    preparationTimeMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    authorEmail: 'heston@recipenest.com',
    ingredients: [
      { name: 'Pork belly (skin-on)', quantity: '1.5 kg', orderIndex: 0 },
      { name: 'Fennel seeds', quantity: '1 tbsp', orderIndex: 1 },
      { name: 'Garlic cloves', quantity: '4', orderIndex: 2 },
      { name: 'Apple juice', quantity: '200 ml', orderIndex: 3 },
      { name: 'Thyme sprigs', quantity: '4', orderIndex: 4 },
      { name: 'Bay leaves', quantity: '2', orderIndex: 5 },
      { name: 'Fleur de sel', quantity: '2 tbsp', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Score the pork skin deeply. Rub all over with fennel seeds, garlic, salt, and pepper. Refrigerate uncovered overnight.', orderIndex: 0 },
      { stepText: 'Place pork in a roasting tin with apple juice, thyme, and bay leaves. Cover tightly with foil. Roast at 90�C (195�F) for 6 hours until very tender.', orderIndex: 1 },
      { stepText: 'Remove foil, increase oven to 220�C (425�F), and roast for 30 minutes to crisp the skin. If needed, finish under a hot grill.', orderIndex: 2 },
      { stepText: 'Rest for 15 minutes. Slice and serve with apple sauce and roasted vegetables.', orderIndex: 3 },
    ],
  },
  {
    title: 'Smoked Salmon Rillettes',
    description: 'A luxurious smoked salmon spread with cream cheese, lemon, and dill � served on crisp blinis.',
    category: 'Snack',
    difficulty: 'Easy',
    preparationTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800',
    authorEmail: 'heston@recipenest.com',
    ingredients: [
      { name: 'Smoked salmon', quantity: '200 g', orderIndex: 0 },
      { name: 'Cream cheese', quantity: '150 g', orderIndex: 1 },
      { name: 'Lemon juice', quantity: '2 tbsp', orderIndex: 2 },
      { name: 'Fresh dill', quantity: '2 tbsp', orderIndex: 3 },
      { name: 'Capers', quantity: '1 tbsp', orderIndex: 4 },
      { name: 'Blinis', quantity: '16', orderIndex: 5 },
      { name: 'Black pepper', quantity: 'to taste', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Roughly chop half the smoked salmon. Flake the other half into larger pieces.', orderIndex: 0 },
      { stepText: 'Mix cream cheese with lemon juice, dill, and capers until smooth. Fold in all the salmon.', orderIndex: 1 },
      { stepText: 'Season with black pepper (no salt needed � the salmon is salty enough).', orderIndex: 2 },
      { stepText: 'Serve on warm blinis with a sprig of dill and a squeeze of lemon.', orderIndex: 3 },
    ],
  },
  {
    title: 'Nitro Scrambled Eggs',
    description: 'Heston\'s theatrical take on scrambled eggs � cooked with liquid nitrogen for an impossibly light, airy texture.',
    category: 'Breakfast',
    difficulty: 'Hard',
    preparationTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800',
    authorEmail: 'heston@recipenest.com',
    ingredients: [
      { name: 'Large eggs', quantity: '8', orderIndex: 0 },
      { name: 'Double cream', quantity: '100 ml', orderIndex: 1 },
      { name: 'Unsalted butter', quantity: '40 g', orderIndex: 2 },
      { name: 'Truffle oil', quantity: '1 tsp', orderIndex: 3 },
      { name: 'Chives', quantity: '2 tbsp', orderIndex: 4 },
      { name: 'Salt and white pepper', quantity: 'to taste', orderIndex: 5 },
    ],
    instructions: [
      { stepText: 'Whisk eggs with cream, salt, and white pepper until very well combined.', orderIndex: 0 },
      { stepText: 'Cook in a bain-marie over barely simmering water, stirring constantly with a spatula, for 15�20 minutes until very slowly set and ultra-creamy.', orderIndex: 1 },
      { stepText: 'Remove from heat, stir in butter and truffle oil.', orderIndex: 2 },
      { stepText: 'Serve in eggshells or small cups, topped with chives. The key is patience � low and slow creates the silkiest texture.', orderIndex: 3 },
    ],
  },
  {
    title: 'Caramelised Onion Tart',
    description: 'A rich, deeply caramelised onion tart in a buttery pastry shell with Gruy�re and fresh thyme.',
    category: 'Lunch',
    difficulty: 'Medium',
    preparationTimeMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1571091655789-405eb7a3a3a8?w=800',
    authorEmail: 'heston@recipenest.com',
    ingredients: [
      { name: 'Yellow onions', quantity: '1 kg', orderIndex: 0 },
      { name: 'Shortcrust pastry', quantity: '300 g', orderIndex: 1 },
      { name: 'Eggs', quantity: '3', orderIndex: 2 },
      { name: 'Double cream', quantity: '200 ml', orderIndex: 3 },
      { name: 'Gruy�re, grated', quantity: '100 g', orderIndex: 4 },
      { name: 'Fresh thyme', quantity: '1 tbsp', orderIndex: 5 },
      { name: 'Unsalted butter', quantity: '50 g', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Slice onions thinly. Cook in butter over very low heat for 60�75 minutes, stirring occasionally, until deeply golden and jammy.', orderIndex: 0 },
      { stepText: 'Roll out pastry and line a 23 cm tart tin. Blind bake at 190�C (375�F) for 15 minutes.', orderIndex: 1 },
      { stepText: 'Whisk eggs with cream, thyme, salt, and pepper. Stir in caramelised onions and half the Gruy�re.', orderIndex: 2 },
      { stepText: 'Pour into the pastry case, top with remaining Gruy�re, and bake at 180�C (350�F) for 30 minutes until golden and just set.', orderIndex: 3 },
    ],
  },
  // -- Massimo Bottura (5 recipes) --------------------------------------------
  {
    title: 'Tagliatelle al Rag�',
    description: 'Massimo\'s slow-cooked Bolognese rag� with hand-rolled egg tagliatelle � a reverent homage to Emilian tradition.',
    category: 'Dinner',
    difficulty: 'Hard',
    preparationTimeMinutes: 240,
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
    authorEmail: 'massimo@recipenest.com',
    ingredients: [
      { name: 'Minced beef', quantity: '300 g', orderIndex: 0 },
      { name: 'Minced pork', quantity: '200 g', orderIndex: 1 },
      { name: 'Pancetta', quantity: '100 g', orderIndex: 2 },
      { name: 'Dry white wine', quantity: '150 ml', orderIndex: 3 },
      { name: 'Whole milk', quantity: '100 ml', orderIndex: 4 },
      { name: 'Canned tomatoes', quantity: '200 g', orderIndex: 5 },
      { name: 'Egg tagliatelle', quantity: '400 g', orderIndex: 6 },
      { name: 'Parmigiano Reggiano', quantity: '80 g', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Finely dice pancetta and render in a heavy pot. Add minced meats and brown thoroughly, breaking up any lumps.', orderIndex: 0 },
      { stepText: 'Add wine and cook until evaporated. Add milk and cook until absorbed. Add tomatoes.', orderIndex: 1 },
      { stepText: 'Simmer on the lowest possible heat for 3�4 hours, adding a splash of water if it dries out. The rag� should be rich and barely saucy.', orderIndex: 2 },
      { stepText: 'Cook tagliatelle in well-salted water. Toss with rag� and a ladleful of pasta water. Finish with Parmigiano and serve.', orderIndex: 3 },
    ],
  },
  {
    title: 'Risotto Cacio e Pepe',
    description: 'A Roman-inspired risotto with the bold flavours of cacio e pepe � Pecorino, Parmesan, and an abundance of black pepper.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 40,
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800',
    authorEmail: 'massimo@recipenest.com',
    ingredients: [
      { name: 'Carnaroli rice', quantity: '320 g', orderIndex: 0 },
      { name: 'Vegetable stock', quantity: '1.2 litres', orderIndex: 1 },
      { name: 'Pecorino Romano, grated', quantity: '80 g', orderIndex: 2 },
      { name: 'Parmigiano Reggiano, grated', quantity: '60 g', orderIndex: 3 },
      { name: 'Unsalted butter', quantity: '60 g', orderIndex: 4 },
      { name: 'Dry white wine', quantity: '100 ml', orderIndex: 5 },
      { name: 'Black pepper, coarsely ground', quantity: '2 tsp', orderIndex: 6 },
      { name: 'Shallot', quantity: '1', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Saut� shallot in butter until soft. Add rice and toast for 2 minutes. Add wine and stir until absorbed.', orderIndex: 0 },
      { stepText: 'Add hot stock one ladle at a time, stirring constantly and waiting for each addition to be absorbed before adding the next. Cook for 18 minutes.', orderIndex: 1 },
      { stepText: 'Remove from heat. Stir in cold butter, Pecorino, and Parmesan vigorously to create a creamy, flowing consistency (mantecatura).', orderIndex: 2 },
      { stepText: 'Add a generous amount of coarsely ground black pepper. Rest for 1 minute, then serve immediately on warm plates.', orderIndex: 3 },
    ],
  },
  {
    title: 'Tiramisu',
    description: 'The classic Italian dessert � espresso-soaked savoiardi layered with a cloud-like mascarpone cream and dusted with cocoa.',
    category: 'Dessert',
    difficulty: 'Medium',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1571197119738-a8b3e8e0e0e0?w=800',
    authorEmail: 'massimo@recipenest.com',
    ingredients: [
      { name: 'Savoiardi (ladyfinger biscuits)', quantity: '200 g', orderIndex: 0 },
      { name: 'Mascarpone', quantity: '500 g', orderIndex: 1 },
      { name: 'Eggs, separated', quantity: '4', orderIndex: 2 },
      { name: 'Caster sugar', quantity: '100 g', orderIndex: 3 },
      { name: 'Strong espresso, cooled', quantity: '300 ml', orderIndex: 4 },
      { name: 'Marsala wine', quantity: '3 tbsp', orderIndex: 5 },
      { name: 'Cocoa powder', quantity: '3 tbsp', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Whisk egg yolks with sugar until pale and thick. Beat in mascarpone until smooth.', orderIndex: 0 },
      { stepText: 'Whisk egg whites to stiff peaks. Fold gently into the mascarpone mixture in three additions.', orderIndex: 1 },
      { stepText: 'Mix espresso with Marsala. Quickly dip each savoiardo and layer in a dish. Spread half the cream over. Repeat layers.', orderIndex: 2 },
      { stepText: 'Dust generously with cocoa powder. Refrigerate for at least 4 hours (overnight is best) before serving.', orderIndex: 3 },
    ],
  },
  {
    title: 'Bruschetta al Pomodoro',
    description: 'The simplest and most perfect Italian antipasto � grilled bread rubbed with garlic and topped with ripe tomatoes and basil.',
    category: 'Snack',
    difficulty: 'Easy',
    preparationTimeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800',
    authorEmail: 'massimo@recipenest.com',
    ingredients: [
      { name: 'Sourdough or ciabatta', quantity: '8 slices', orderIndex: 0 },
      { name: 'Ripe tomatoes', quantity: '4 large', orderIndex: 1 },
      { name: 'Garlic cloves', quantity: '2', orderIndex: 2 },
      { name: 'Fresh basil', quantity: 'large handful', orderIndex: 3 },
      { name: 'Extra virgin olive oil', quantity: '4 tbsp', orderIndex: 4 },
      { name: 'Fleur de sel', quantity: 'to taste', orderIndex: 5 },
      { name: 'Black pepper', quantity: 'to taste', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Dice tomatoes and toss with torn basil, olive oil, salt, and pepper. Let marinate for 10 minutes.', orderIndex: 0 },
      { stepText: 'Grill or toast bread slices until golden and charred at the edges.', orderIndex: 1 },
      { stepText: 'Immediately rub each slice with a cut garlic clove while still hot.', orderIndex: 2 },
      { stepText: 'Spoon tomato mixture generously over the bread. Drizzle with more olive oil and serve at once.', orderIndex: 3 },
    ],
  },
  {
    title: 'Panna Cotta with Caramel',
    description: 'A silky, barely-set vanilla panna cotta with a golden salted caramel sauce � Italian elegance at its simplest.',
    category: 'Dessert',
    difficulty: 'Easy',
    preparationTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
    authorEmail: 'massimo@recipenest.com',
    ingredients: [
      { name: 'Double cream', quantity: '500 ml', orderIndex: 0 },
      { name: 'Whole milk', quantity: '100 ml', orderIndex: 1 },
      { name: 'Caster sugar', quantity: '60 g', orderIndex: 2 },
      { name: 'Vanilla pod', quantity: '1', orderIndex: 3 },
      { name: 'Gelatine leaves', quantity: '3', orderIndex: 4 },
      { name: 'Brown sugar (for caramel)', quantity: '100 g', orderIndex: 5 },
      { name: 'Sea salt flakes', quantity: 'pinch', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Soak gelatine in cold water for 5 minutes. Heat cream, milk, sugar, and vanilla pod until just simmering. Remove vanilla.', orderIndex: 0 },
      { stepText: 'Squeeze out gelatine and stir into the hot cream until dissolved. Pour into 4 lightly oiled moulds. Refrigerate for 4 hours.', orderIndex: 1 },
      { stepText: 'Melt brown sugar in a dry pan until amber. Add a splash of cream and a pinch of sea salt; stir to a smooth caramel.', orderIndex: 2 },
      { stepText: 'Unmould panna cotta onto plates and spoon salted caramel over the top. Serve immediately.', orderIndex: 3 },
    ],
  },
  // -- Nobu Matsuhisa (5 recipes) ---------------------------------------------
  {
    title: 'Miso Black Cod',
    description: 'Nobu\'s iconic black cod marinated in sweet white miso for 2�3 days, then broiled to a caramelised, melt-in-the-mouth perfection.',
    category: 'Dinner',
    difficulty: 'Medium',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800',
    authorEmail: 'nobu@recipenest.com',
    ingredients: [
      { name: 'Black cod fillets', quantity: '4 x 180 g', orderIndex: 0 },
      { name: 'White miso paste', quantity: '200 g', orderIndex: 1 },
      { name: 'Mirin', quantity: '3 tbsp', orderIndex: 2 },
      { name: 'Sake', quantity: '3 tbsp', orderIndex: 3 },
      { name: 'Caster sugar', quantity: '3 tbsp', orderIndex: 4 },
      { name: 'Pickled ginger', quantity: 'to serve', orderIndex: 5 },
    ],
    instructions: [
      { stepText: 'Combine miso, mirin, sake, and sugar in a pan. Heat gently, stirring, until sugar dissolves. Cool completely.', orderIndex: 0 },
      { stepText: 'Pat cod dry. Coat generously in the miso marinade. Cover and refrigerate for 2�3 days.', orderIndex: 1 },
      { stepText: 'Wipe off excess marinade (it will burn). Place cod on a foil-lined tray.', orderIndex: 2 },
      { stepText: 'Broil/grill for 8�10 minutes until deeply caramelised and cooked through. Serve with pickled ginger and steamed rice.', orderIndex: 3 },
    ],
  },
  {
    title: 'Yellowtail Sashimi with Jalape�o',
    description: 'Nobu\'s signature dish � thin slices of yellowtail with a yuzu-soy dressing and fresh jalape�o.',
    category: 'Lunch',
    difficulty: 'Easy',
    preparationTimeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800',
    authorEmail: 'nobu@recipenest.com',
    ingredients: [
      { name: 'Sashimi-grade yellowtail', quantity: '300 g', orderIndex: 0 },
      { name: 'Jalape�o', quantity: '1', orderIndex: 1 },
      { name: 'Yuzu juice', quantity: '2 tbsp', orderIndex: 2 },
      { name: 'Soy sauce', quantity: '2 tbsp', orderIndex: 3 },
      { name: 'Sesame oil', quantity: '1 tsp', orderIndex: 4 },
      { name: 'Micro herbs or coriander', quantity: 'to garnish', orderIndex: 5 },
      { name: 'Garlic oil', quantity: '1 tsp', orderIndex: 6 },
    ],
    instructions: [
      { stepText: 'Slice yellowtail very thinly (about 3 mm) and arrange in a single layer on a chilled plate.', orderIndex: 0 },
      { stepText: 'Slice jalape�o into thin rounds and place one on each piece of fish.', orderIndex: 1 },
      { stepText: 'Mix yuzu juice, soy sauce, sesame oil, and garlic oil. Drizzle over the fish.', orderIndex: 2 },
      { stepText: 'Garnish with micro herbs and serve immediately while the fish is cold.', orderIndex: 3 },
    ],
  },
  {
    title: 'Spicy Tuna Rolls',
    description: 'Classic spicy tuna maki rolls with a creamy sriracha mayo filling and sesame seeds.',
    category: 'Lunch',
    difficulty: 'Medium',
    preparationTimeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
    authorEmail: 'nobu@recipenest.com',
    ingredients: [
      { name: 'Sushi rice', quantity: '300 g', orderIndex: 0 },
      { name: 'Sashimi-grade tuna', quantity: '200 g', orderIndex: 1 },
      { name: 'Nori sheets', quantity: '4', orderIndex: 2 },
      { name: 'Sriracha', quantity: '2 tbsp', orderIndex: 3 },
      { name: 'Japanese mayonnaise', quantity: '2 tbsp', orderIndex: 4 },
      { name: 'Rice vinegar', quantity: '3 tbsp', orderIndex: 5 },
      { name: 'Sesame seeds', quantity: '2 tbsp', orderIndex: 6 },
      { name: 'Cucumber', quantity: '1/2', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Cook sushi rice. Season with rice vinegar, sugar, and salt while still warm. Fan to cool.', orderIndex: 0 },
      { stepText: 'Finely chop tuna and mix with sriracha and mayonnaise.', orderIndex: 1 },
      { stepText: 'Place nori on a bamboo mat. Spread rice evenly, leaving a 2 cm border. Add tuna and cucumber strips. Roll tightly using the mat.', orderIndex: 2 },
      { stepText: 'Slice into 6�8 pieces with a wet knife. Sprinkle with sesame seeds and serve with soy sauce and pickled ginger.', orderIndex: 3 },
    ],
  },
  {
    title: 'Ramen with Chashu Pork',
    description: 'A rich tonkotsu-style ramen broth with melt-in-the-mouth chashu pork belly, soft-boiled eggs, and noodles.',
    category: 'Dinner',
    difficulty: 'Hard',
    preparationTimeMinutes: 300,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
    authorEmail: 'nobu@recipenest.com',
    ingredients: [
      { name: 'Pork belly', quantity: '600 g', orderIndex: 0 },
      { name: 'Ramen noodles', quantity: '400 g', orderIndex: 1 },
      { name: 'Pork bones', quantity: '1 kg', orderIndex: 2 },
      { name: 'Soy sauce', quantity: '4 tbsp', orderIndex: 3 },
      { name: 'Mirin', quantity: '3 tbsp', orderIndex: 4 },
      { name: 'Eggs', quantity: '4', orderIndex: 5 },
      { name: 'Spring onions', quantity: '4', orderIndex: 6 },
      { name: 'Nori sheets', quantity: '4', orderIndex: 7 },
    ],
    instructions: [
      { stepText: 'Blanch pork bones, then simmer in fresh water for 4 hours to make a rich broth. Season with soy sauce and mirin.', orderIndex: 0 },
      { stepText: 'Roll pork belly tightly and tie with string. Braise in soy sauce, mirin, and water for 2 hours until tender. Slice when cool.', orderIndex: 1 },
      { stepText: 'Soft-boil eggs for 6.5 minutes. Peel and marinate in soy sauce and mirin for 1 hour.', orderIndex: 2 },
      { stepText: 'Cook noodles. Ladle hot broth into bowls, add noodles, sliced chashu, halved marinated egg, spring onions, and nori. Serve immediately.', orderIndex: 3 },
    ],
  },
  {
    title: 'Matcha Ice Cream',
    description: 'Intensely flavoured Japanese matcha ice cream � creamy, slightly bitter, and utterly addictive.',
    category: 'Dessert',
    difficulty: 'Medium',
    preparationTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
    authorEmail: 'nobu@recipenest.com',
    ingredients: [
      { name: 'Double cream', quantity: '300 ml', orderIndex: 0 },
      { name: 'Whole milk', quantity: '200 ml', orderIndex: 1 },
      { name: 'Ceremonial matcha powder', quantity: '3 tbsp', orderIndex: 2 },
      { name: 'Egg yolks', quantity: '4', orderIndex: 3 },
      { name: 'Caster sugar', quantity: '120 g', orderIndex: 4 },
      { name: 'Pinch of salt', quantity: '1 pinch', orderIndex: 5 },
    ],
    instructions: [
      { stepText: 'Whisk matcha with 3 tbsp hot water until smooth. Heat cream and milk until just simmering.', orderIndex: 0 },
      { stepText: 'Whisk egg yolks with sugar until pale. Slowly pour in hot cream, whisking constantly. Return to the pan and cook over low heat, stirring, until the custard coats a spoon.', orderIndex: 1 },
      { stepText: 'Stir in matcha paste and a pinch of salt. Strain and cool over an ice bath.', orderIndex: 2 },
      { stepText: 'Churn in an ice cream machine according to manufacturer\'s instructions. Freeze for 2 hours before serving.', orderIndex: 3 },
    ],
  },
]

// --- Create Recipes ----------------------------------------------------------
console.log('\n?? Seeding recipes...')
const createdRecipes = []
for (const r of recipesData) {
  const author = createdUsers[r.authorEmail]
  if (!author) { console.warn(`  ? No user found for ${r.authorEmail}`); continue }
  let recipe = await Recipe.findOne({ title: r.title, author: author._id })
  if (!recipe) {
    recipe = await Recipe.create({
      title: r.title,
      description: r.description,
      category: r.category,
      difficulty: r.difficulty,
      preparationTimeMinutes: r.preparationTimeMinutes,
      imageUrl: r.imageUrl,
      author: author._id,
      ingredients: r.ingredients,
      instructions: r.instructions,
    })
    console.log(`  ? Created recipe: ${r.title}`)
  } else {
    console.log(`  � Skipped recipe (exists): ${r.title}`)
  }
  createdRecipes.push(recipe)
}

// --- Follows -----------------------------------------------------------------
console.log('\n?? Seeding follows...')
const followPairs = [
  [gordon._id, julia._id],
  [gordon._id, jamie._id],
  [gordon._id, thomas._id],
  [julia._id, gordon._id],
  [julia._id, nigella._id],
  [julia._id, ina._id],
  [jamie._id, gordon._id],
  [jamie._id, yotam._id],
  [jamie._id, nigella._id],
  [yotam._id, julia._id],
  [yotam._id, massimo._id],
  [yotam._id, nobu._id],
  [nigella._id, julia._id],
  [nigella._id, ina._id],
  [nigella._id, heston._id],
  [thomas._id, gordon._id],
  [thomas._id, massimo._id],
  [thomas._id, heston._id],
  [ina._id, julia._id],
  [ina._id, nigella._id],
  [ina._id, jamie._id],
  [heston._id, thomas._id],
  [heston._id, massimo._id],
  [heston._id, nobu._id],
  [massimo._id, julia._id],
  [massimo._id, nobu._id],
  [massimo._id, thomas._id],
  [nobu._id, massimo._id],
  [nobu._id, heston._id],
  [nobu._id, gordon._id],
]
for (const [follower, following] of followPairs) {
  try {
    await Follow.create({ follower, following })
    console.log(`  ? Follow created`)
  } catch {
    console.log(`  � Follow already exists`)
  }
}

// --- Likes -------------------------------------------------------------------
console.log('\n??  Seeding likes...')
const likeAssignments = [
  { userEmail: 'julia@recipenest.com',   recipeIndex: 0  },
  { userEmail: 'jamie@recipenest.com',   recipeIndex: 0  },
  { userEmail: 'thomas@recipenest.com',  recipeIndex: 0  },
  { userEmail: 'ina@recipenest.com',     recipeIndex: 1  },
  { userEmail: 'nigella@recipenest.com', recipeIndex: 1  },
  { userEmail: 'gordon@recipenest.com',  recipeIndex: 5  },
  { userEmail: 'yotam@recipenest.com',   recipeIndex: 5  },
  { userEmail: 'heston@recipenest.com',  recipeIndex: 5  },
  { userEmail: 'gordon@recipenest.com',  recipeIndex: 10 },
  { userEmail: 'julia@recipenest.com',   recipeIndex: 10 },
  { userEmail: 'massimo@recipenest.com', recipeIndex: 10 },
  { userEmail: 'nobu@recipenest.com',    recipeIndex: 15 },
  { userEmail: 'gordon@recipenest.com',  recipeIndex: 15 },
  { userEmail: 'ina@recipenest.com',     recipeIndex: 20 },
  { userEmail: 'jamie@recipenest.com',   recipeIndex: 20 },
  { userEmail: 'thomas@recipenest.com',  recipeIndex: 25 },
  { userEmail: 'heston@recipenest.com',  recipeIndex: 25 },
  { userEmail: 'massimo@recipenest.com', recipeIndex: 30 },
  { userEmail: 'nobu@recipenest.com',    recipeIndex: 35 },
  { userEmail: 'yotam@recipenest.com',   recipeIndex: 40 },
  { userEmail: 'nigella@recipenest.com', recipeIndex: 45 },
  { userEmail: 'julia@recipenest.com',   recipeIndex: 45 },
]
for (const { userEmail, recipeIndex } of likeAssignments) {
  const user = createdUsers[userEmail]
  const recipe = createdRecipes[recipeIndex]
  if (!user || !recipe) continue
  try {
    await Like.create({ user: user._id, recipe: recipe._id })
    await Recipe.findByIdAndUpdate(recipe._id, { $inc: { likeCount: 1 } })
    console.log(`  ? Like added`)
  } catch {
    console.log(`  � Like already exists`)
  }
}

// --- Summary -----------------------------------------------------------------
console.log('\n' + '-'.repeat(72))
console.log('  SEED COMPLETE � USER CREDENTIALS')
console.log('-'.repeat(72))
console.log(
  'Name'.padEnd(22) +
  'Email'.padEnd(28) +
  'Password'
)
console.log('-'.repeat(72))
for (const u of usersData) {
  console.log(
    u.displayName.padEnd(22) +
    u.email.padEnd(28) +
    u.password
  )
}
console.log('-'.repeat(72))
console.log(`\n  Users:   ${usersData.length}`)
console.log(`  Recipes: ${createdRecipes.length}`)
console.log(`  Follows: ${followPairs.length}`)
console.log(`  Likes:   ${likeAssignments.length}`)
console.log('-'.repeat(72) + '\n')

// --- Disconnect --------------------------------------------------------------
await mongoose.disconnect()
console.log('? Disconnected from MongoDB')
